services:
  - type: web
    name: leafengines-emergency-api-1
    runtime: python
    python:
      version: 3.12.0  # Compatible with psycopg2-binary
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
